// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DownloadPrefs.proto

package com.zk.car.upgrade;

/**
 * Protobuf type {@code DownloadProgress}
 */
public  final class DownloadProgress extends
    com.google.protobuf.GeneratedMessageLite<
        DownloadProgress, DownloadProgress.Builder> implements
    // @@protoc_insertion_point(message_implements:DownloadProgress)
    DownloadProgressOrBuilder {
  private DownloadProgress() {
  }
  public static final int PROGRESS_FIELD_NUMBER = 1;
  private long progress_;
  /**
   * <code>int64 progress = 1;</code>
   * @return The progress.
   */
  @java.lang.Override
  public long getProgress() {
    return progress_;
  }
  /**
   * <code>int64 progress = 1;</code>
   * @param value The progress to set.
   */
  private void setProgress(long value) {
    
    progress_ = value;
  }
  /**
   * <code>int64 progress = 1;</code>
   */
  private void clearProgress() {
    
    progress_ = 0L;
  }

  public static final int TOTAL_FIELD_NUMBER = 2;
  private long total_;
  /**
   * <code>int64 total = 2;</code>
   * @return The total.
   */
  @java.lang.Override
  public long getTotal() {
    return total_;
  }
  /**
   * <code>int64 total = 2;</code>
   * @param value The total to set.
   */
  private void setTotal(long value) {
    
    total_ = value;
  }
  /**
   * <code>int64 total = 2;</code>
   */
  private void clearTotal() {
    
    total_ = 0L;
  }

  public static final int ISDONE_FIELD_NUMBER = 3;
  private boolean isDone_;
  /**
   * <code>bool isDone = 3;</code>
   * @return The isDone.
   */
  @java.lang.Override
  public boolean getIsDone() {
    return isDone_;
  }
  /**
   * <code>bool isDone = 3;</code>
   * @param value The isDone to set.
   */
  private void setIsDone(boolean value) {
    
    isDone_ = value;
  }
  /**
   * <code>bool isDone = 3;</code>
   */
  private void clearIsDone() {
    
    isDone_ = false;
  }

  public static com.zk.car.upgrade.DownloadProgress parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.zk.car.upgrade.DownloadProgress parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.zk.car.upgrade.DownloadProgress parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.zk.car.upgrade.DownloadProgress parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.zk.car.upgrade.DownloadProgress parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.zk.car.upgrade.DownloadProgress parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.zk.car.upgrade.DownloadProgress parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.zk.car.upgrade.DownloadProgress parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.zk.car.upgrade.DownloadProgress parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.zk.car.upgrade.DownloadProgress parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.zk.car.upgrade.DownloadProgress parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.zk.car.upgrade.DownloadProgress parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.zk.car.upgrade.DownloadProgress prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code DownloadProgress}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.zk.car.upgrade.DownloadProgress, Builder> implements
      // @@protoc_insertion_point(builder_implements:DownloadProgress)
      com.zk.car.upgrade.DownloadProgressOrBuilder {
    // Construct using com.zk.car.upgrade.DownloadProgress.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>int64 progress = 1;</code>
     * @return The progress.
     */
    @java.lang.Override
    public long getProgress() {
      return instance.getProgress();
    }
    /**
     * <code>int64 progress = 1;</code>
     * @param value The progress to set.
     * @return This builder for chaining.
     */
    public Builder setProgress(long value) {
      copyOnWrite();
      instance.setProgress(value);
      return this;
    }
    /**
     * <code>int64 progress = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearProgress() {
      copyOnWrite();
      instance.clearProgress();
      return this;
    }

    /**
     * <code>int64 total = 2;</code>
     * @return The total.
     */
    @java.lang.Override
    public long getTotal() {
      return instance.getTotal();
    }
    /**
     * <code>int64 total = 2;</code>
     * @param value The total to set.
     * @return This builder for chaining.
     */
    public Builder setTotal(long value) {
      copyOnWrite();
      instance.setTotal(value);
      return this;
    }
    /**
     * <code>int64 total = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotal() {
      copyOnWrite();
      instance.clearTotal();
      return this;
    }

    /**
     * <code>bool isDone = 3;</code>
     * @return The isDone.
     */
    @java.lang.Override
    public boolean getIsDone() {
      return instance.getIsDone();
    }
    /**
     * <code>bool isDone = 3;</code>
     * @param value The isDone to set.
     * @return This builder for chaining.
     */
    public Builder setIsDone(boolean value) {
      copyOnWrite();
      instance.setIsDone(value);
      return this;
    }
    /**
     * <code>bool isDone = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsDone() {
      copyOnWrite();
      instance.clearIsDone();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:DownloadProgress)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.zk.car.upgrade.DownloadProgress();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "progress_",
            "total_",
            "isDone_",
          };
          java.lang.String info =
              "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u0002\u0002\u0002" +
              "\u0003\u0007";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.zk.car.upgrade.DownloadProgress> parser = PARSER;
        if (parser == null) {
          synchronized (com.zk.car.upgrade.DownloadProgress.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.zk.car.upgrade.DownloadProgress>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:DownloadProgress)
  private static final com.zk.car.upgrade.DownloadProgress DEFAULT_INSTANCE;
  static {
    DownloadProgress defaultInstance = new DownloadProgress();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      DownloadProgress.class, defaultInstance);
  }

  public static com.zk.car.upgrade.DownloadProgress getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<DownloadProgress> PARSER;

  public static com.google.protobuf.Parser<DownloadProgress> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

