// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DownloadPrefs.proto

package com.zk.car.upgrade;

public interface DownloadProgressOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DownloadProgress)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>int64 progress = 1;</code>
   * @return The progress.
   */
  long getProgress();

  /**
   * <code>int64 total = 2;</code>
   * @return The total.
   */
  long getTotal();

  /**
   * <code>bool isDone = 3;</code>
   * @return The isDone.
   */
  boolean getIsDone();
}
