// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: McuVersionPrefs.proto

package com.zk.car.upgrade;

public interface McuVersionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:McuVersion)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>int32 mcu_upgrade_status = 1;</code>
   * @return The mcuUpgradeStatus.
   */
  int getMcuUpgradeStatus();

  /**
   * <code>int32 mcu_request_payload_data = 2;</code>
   * @return The mcuRequestPayloadData.
   */
  int getMcuRequestPayloadData();

  /**
   * <code>int32 mcu_upgrade_raedy_status = 3;</code>
   * @return The mcuUpgradeRaedyStatus.
   */
  int getMcuUpgradeRaedyStatus();

  /**
   * <code>int32 mcu_run_position = 4;</code>
   * @return The mcuRunPosition.
   */
  int getMcuRunPosition();

  /**
   * <code>int32 mcu_current_position_program_status = 5;</code>
   * @return The mcuCurrentPositionProgramStatus.
   */
  int getMcuCurrentPositionProgramStatus();

  /**
   * <code>int32 mcu_upgrade_fail = 6;</code>
   * @return The mcuUpgradeFail.
   */
  int getMcuUpgradeFail();

  /**
   * <code>int64 mcu_retransmission_block_num = 7;</code>
   * @return The mcuRetransmissionBlockNum.
   */
  long getMcuRetransmissionBlockNum();

  /**
   * <code>string mcu_pbl_version = 8;</code>
   * @return The mcuPblVersion.
   */
  java.lang.String getMcuPblVersion();
  /**
   * <code>string mcu_pbl_version = 8;</code>
   * @return The bytes for mcuPblVersion.
   */
  com.google.protobuf.ByteString
      getMcuPblVersionBytes();

  /**
   * <code>string mcu_a_version = 9;</code>
   * @return The mcuAVersion.
   */
  java.lang.String getMcuAVersion();
  /**
   * <code>string mcu_a_version = 9;</code>
   * @return The bytes for mcuAVersion.
   */
  com.google.protobuf.ByteString
      getMcuAVersionBytes();

  /**
   * <code>string mcu_b_version = 10;</code>
   * @return The mcuBVersion.
   */
  java.lang.String getMcuBVersion();
  /**
   * <code>string mcu_b_version = 10;</code>
   * @return The bytes for mcuBVersion.
   */
  com.google.protobuf.ByteString
      getMcuBVersionBytes();

  /**
   * <code>string mcu_nvm_version = 11;</code>
   * @return The mcuNvmVersion.
   */
  java.lang.String getMcuNvmVersion();
  /**
   * <code>string mcu_nvm_version = 11;</code>
   * @return The bytes for mcuNvmVersion.
   */
  com.google.protobuf.ByteString
      getMcuNvmVersionBytes();

  /**
   * <code>int32 mcu_upgrade_file_transfer_status = 12;</code>
   * @return The mcuUpgradeFileTransferStatus.
   */
  int getMcuUpgradeFileTransferStatus();

  /**
   * <code>string mcu_update_bean = 13;</code>
   * @return The mcuUpdateBean.
   */
  java.lang.String getMcuUpdateBean();
  /**
   * <code>string mcu_update_bean = 13;</code>
   * @return The bytes for mcuUpdateBean.
   */
  com.google.protobuf.ByteString
      getMcuUpdateBeanBytes();
}
