// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: McuVersionPrefs.proto

package com.zk.car.upgrade;

/**
 * Protobuf type {@code McuVersion}
 */
public  final class McuVersion extends
    com.google.protobuf.GeneratedMessageLite<
        McuVersion, McuVersion.Builder> implements
    // @@protoc_insertion_point(message_implements:McuVersion)
    McuVersionOrBuilder {
  private McuVersion() {
    mcuPblVersion_ = "";
    mcuAVersion_ = "";
    mcuBVersion_ = "";
    mcuNvmVersion_ = "";
    mcuUpdateBean_ = "";
  }
  public static final int MCU_UPGRADE_STATUS_FIELD_NUMBER = 1;
  private int mcuUpgradeStatus_;
  /**
   * <code>int32 mcu_upgrade_status = 1;</code>
   * @return The mcuUpgradeStatus.
   */
  @java.lang.Override
  public int getMcuUpgradeStatus() {
    return mcuUpgradeStatus_;
  }
  /**
   * <code>int32 mcu_upgrade_status = 1;</code>
   * @param value The mcuUpgradeStatus to set.
   */
  private void setMcuUpgradeStatus(int value) {
    
    mcuUpgradeStatus_ = value;
  }
  /**
   * <code>int32 mcu_upgrade_status = 1;</code>
   */
  private void clearMcuUpgradeStatus() {
    
    mcuUpgradeStatus_ = 0;
  }

  public static final int MCU_REQUEST_PAYLOAD_DATA_FIELD_NUMBER = 2;
  private int mcuRequestPayloadData_;
  /**
   * <code>int32 mcu_request_payload_data = 2;</code>
   * @return The mcuRequestPayloadData.
   */
  @java.lang.Override
  public int getMcuRequestPayloadData() {
    return mcuRequestPayloadData_;
  }
  /**
   * <code>int32 mcu_request_payload_data = 2;</code>
   * @param value The mcuRequestPayloadData to set.
   */
  private void setMcuRequestPayloadData(int value) {
    
    mcuRequestPayloadData_ = value;
  }
  /**
   * <code>int32 mcu_request_payload_data = 2;</code>
   */
  private void clearMcuRequestPayloadData() {
    
    mcuRequestPayloadData_ = 0;
  }

  public static final int MCU_UPGRADE_RAEDY_STATUS_FIELD_NUMBER = 3;
  private int mcuUpgradeRaedyStatus_;
  /**
   * <code>int32 mcu_upgrade_raedy_status = 3;</code>
   * @return The mcuUpgradeRaedyStatus.
   */
  @java.lang.Override
  public int getMcuUpgradeRaedyStatus() {
    return mcuUpgradeRaedyStatus_;
  }
  /**
   * <code>int32 mcu_upgrade_raedy_status = 3;</code>
   * @param value The mcuUpgradeRaedyStatus to set.
   */
  private void setMcuUpgradeRaedyStatus(int value) {
    
    mcuUpgradeRaedyStatus_ = value;
  }
  /**
   * <code>int32 mcu_upgrade_raedy_status = 3;</code>
   */
  private void clearMcuUpgradeRaedyStatus() {
    
    mcuUpgradeRaedyStatus_ = 0;
  }

  public static final int MCU_RUN_POSITION_FIELD_NUMBER = 4;
  private int mcuRunPosition_;
  /**
   * <code>int32 mcu_run_position = 4;</code>
   * @return The mcuRunPosition.
   */
  @java.lang.Override
  public int getMcuRunPosition() {
    return mcuRunPosition_;
  }
  /**
   * <code>int32 mcu_run_position = 4;</code>
   * @param value The mcuRunPosition to set.
   */
  private void setMcuRunPosition(int value) {
    
    mcuRunPosition_ = value;
  }
  /**
   * <code>int32 mcu_run_position = 4;</code>
   */
  private void clearMcuRunPosition() {
    
    mcuRunPosition_ = 0;
  }

  public static final int MCU_CURRENT_POSITION_PROGRAM_STATUS_FIELD_NUMBER = 5;
  private int mcuCurrentPositionProgramStatus_;
  /**
   * <code>int32 mcu_current_position_program_status = 5;</code>
   * @return The mcuCurrentPositionProgramStatus.
   */
  @java.lang.Override
  public int getMcuCurrentPositionProgramStatus() {
    return mcuCurrentPositionProgramStatus_;
  }
  /**
   * <code>int32 mcu_current_position_program_status = 5;</code>
   * @param value The mcuCurrentPositionProgramStatus to set.
   */
  private void setMcuCurrentPositionProgramStatus(int value) {
    
    mcuCurrentPositionProgramStatus_ = value;
  }
  /**
   * <code>int32 mcu_current_position_program_status = 5;</code>
   */
  private void clearMcuCurrentPositionProgramStatus() {
    
    mcuCurrentPositionProgramStatus_ = 0;
  }

  public static final int MCU_UPGRADE_FAIL_FIELD_NUMBER = 6;
  private int mcuUpgradeFail_;
  /**
   * <code>int32 mcu_upgrade_fail = 6;</code>
   * @return The mcuUpgradeFail.
   */
  @java.lang.Override
  public int getMcuUpgradeFail() {
    return mcuUpgradeFail_;
  }
  /**
   * <code>int32 mcu_upgrade_fail = 6;</code>
   * @param value The mcuUpgradeFail to set.
   */
  private void setMcuUpgradeFail(int value) {
    
    mcuUpgradeFail_ = value;
  }
  /**
   * <code>int32 mcu_upgrade_fail = 6;</code>
   */
  private void clearMcuUpgradeFail() {
    
    mcuUpgradeFail_ = 0;
  }

  public static final int MCU_RETRANSMISSION_BLOCK_NUM_FIELD_NUMBER = 7;
  private long mcuRetransmissionBlockNum_;
  /**
   * <code>int64 mcu_retransmission_block_num = 7;</code>
   * @return The mcuRetransmissionBlockNum.
   */
  @java.lang.Override
  public long getMcuRetransmissionBlockNum() {
    return mcuRetransmissionBlockNum_;
  }
  /**
   * <code>int64 mcu_retransmission_block_num = 7;</code>
   * @param value The mcuRetransmissionBlockNum to set.
   */
  private void setMcuRetransmissionBlockNum(long value) {
    
    mcuRetransmissionBlockNum_ = value;
  }
  /**
   * <code>int64 mcu_retransmission_block_num = 7;</code>
   */
  private void clearMcuRetransmissionBlockNum() {
    
    mcuRetransmissionBlockNum_ = 0L;
  }

  public static final int MCU_PBL_VERSION_FIELD_NUMBER = 8;
  private java.lang.String mcuPblVersion_;
  /**
   * <code>string mcu_pbl_version = 8;</code>
   * @return The mcuPblVersion.
   */
  @java.lang.Override
  public java.lang.String getMcuPblVersion() {
    return mcuPblVersion_;
  }
  /**
   * <code>string mcu_pbl_version = 8;</code>
   * @return The bytes for mcuPblVersion.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMcuPblVersionBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(mcuPblVersion_);
  }
  /**
   * <code>string mcu_pbl_version = 8;</code>
   * @param value The mcuPblVersion to set.
   */
  private void setMcuPblVersion(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    mcuPblVersion_ = value;
  }
  /**
   * <code>string mcu_pbl_version = 8;</code>
   */
  private void clearMcuPblVersion() {
    
    mcuPblVersion_ = getDefaultInstance().getMcuPblVersion();
  }
  /**
   * <code>string mcu_pbl_version = 8;</code>
   * @param value The bytes for mcuPblVersion to set.
   */
  private void setMcuPblVersionBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    mcuPblVersion_ = value.toStringUtf8();
  }

  public static final int MCU_A_VERSION_FIELD_NUMBER = 9;
  private java.lang.String mcuAVersion_;
  /**
   * <code>string mcu_a_version = 9;</code>
   * @return The mcuAVersion.
   */
  @java.lang.Override
  public java.lang.String getMcuAVersion() {
    return mcuAVersion_;
  }
  /**
   * <code>string mcu_a_version = 9;</code>
   * @return The bytes for mcuAVersion.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMcuAVersionBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(mcuAVersion_);
  }
  /**
   * <code>string mcu_a_version = 9;</code>
   * @param value The mcuAVersion to set.
   */
  private void setMcuAVersion(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    mcuAVersion_ = value;
  }
  /**
   * <code>string mcu_a_version = 9;</code>
   */
  private void clearMcuAVersion() {
    
    mcuAVersion_ = getDefaultInstance().getMcuAVersion();
  }
  /**
   * <code>string mcu_a_version = 9;</code>
   * @param value The bytes for mcuAVersion to set.
   */
  private void setMcuAVersionBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    mcuAVersion_ = value.toStringUtf8();
  }

  public static final int MCU_B_VERSION_FIELD_NUMBER = 10;
  private java.lang.String mcuBVersion_;
  /**
   * <code>string mcu_b_version = 10;</code>
   * @return The mcuBVersion.
   */
  @java.lang.Override
  public java.lang.String getMcuBVersion() {
    return mcuBVersion_;
  }
  /**
   * <code>string mcu_b_version = 10;</code>
   * @return The bytes for mcuBVersion.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMcuBVersionBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(mcuBVersion_);
  }
  /**
   * <code>string mcu_b_version = 10;</code>
   * @param value The mcuBVersion to set.
   */
  private void setMcuBVersion(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    mcuBVersion_ = value;
  }
  /**
   * <code>string mcu_b_version = 10;</code>
   */
  private void clearMcuBVersion() {
    
    mcuBVersion_ = getDefaultInstance().getMcuBVersion();
  }
  /**
   * <code>string mcu_b_version = 10;</code>
   * @param value The bytes for mcuBVersion to set.
   */
  private void setMcuBVersionBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    mcuBVersion_ = value.toStringUtf8();
  }

  public static final int MCU_NVM_VERSION_FIELD_NUMBER = 11;
  private java.lang.String mcuNvmVersion_;
  /**
   * <code>string mcu_nvm_version = 11;</code>
   * @return The mcuNvmVersion.
   */
  @java.lang.Override
  public java.lang.String getMcuNvmVersion() {
    return mcuNvmVersion_;
  }
  /**
   * <code>string mcu_nvm_version = 11;</code>
   * @return The bytes for mcuNvmVersion.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMcuNvmVersionBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(mcuNvmVersion_);
  }
  /**
   * <code>string mcu_nvm_version = 11;</code>
   * @param value The mcuNvmVersion to set.
   */
  private void setMcuNvmVersion(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    mcuNvmVersion_ = value;
  }
  /**
   * <code>string mcu_nvm_version = 11;</code>
   */
  private void clearMcuNvmVersion() {
    
    mcuNvmVersion_ = getDefaultInstance().getMcuNvmVersion();
  }
  /**
   * <code>string mcu_nvm_version = 11;</code>
   * @param value The bytes for mcuNvmVersion to set.
   */
  private void setMcuNvmVersionBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    mcuNvmVersion_ = value.toStringUtf8();
  }

  public static final int MCU_UPGRADE_FILE_TRANSFER_STATUS_FIELD_NUMBER = 12;
  private int mcuUpgradeFileTransferStatus_;
  /**
   * <code>int32 mcu_upgrade_file_transfer_status = 12;</code>
   * @return The mcuUpgradeFileTransferStatus.
   */
  @java.lang.Override
  public int getMcuUpgradeFileTransferStatus() {
    return mcuUpgradeFileTransferStatus_;
  }
  /**
   * <code>int32 mcu_upgrade_file_transfer_status = 12;</code>
   * @param value The mcuUpgradeFileTransferStatus to set.
   */
  private void setMcuUpgradeFileTransferStatus(int value) {
    
    mcuUpgradeFileTransferStatus_ = value;
  }
  /**
   * <code>int32 mcu_upgrade_file_transfer_status = 12;</code>
   */
  private void clearMcuUpgradeFileTransferStatus() {
    
    mcuUpgradeFileTransferStatus_ = 0;
  }

  public static final int MCU_UPDATE_BEAN_FIELD_NUMBER = 13;
  private java.lang.String mcuUpdateBean_;
  /**
   * <code>string mcu_update_bean = 13;</code>
   * @return The mcuUpdateBean.
   */
  @java.lang.Override
  public java.lang.String getMcuUpdateBean() {
    return mcuUpdateBean_;
  }
  /**
   * <code>string mcu_update_bean = 13;</code>
   * @return The bytes for mcuUpdateBean.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMcuUpdateBeanBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(mcuUpdateBean_);
  }
  /**
   * <code>string mcu_update_bean = 13;</code>
   * @param value The mcuUpdateBean to set.
   */
  private void setMcuUpdateBean(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    mcuUpdateBean_ = value;
  }
  /**
   * <code>string mcu_update_bean = 13;</code>
   */
  private void clearMcuUpdateBean() {
    
    mcuUpdateBean_ = getDefaultInstance().getMcuUpdateBean();
  }
  /**
   * <code>string mcu_update_bean = 13;</code>
   * @param value The bytes for mcuUpdateBean to set.
   */
  private void setMcuUpdateBeanBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    mcuUpdateBean_ = value.toStringUtf8();
  }

  public static com.zk.car.upgrade.McuVersion parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.zk.car.upgrade.McuVersion parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.zk.car.upgrade.McuVersion parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.zk.car.upgrade.McuVersion parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.zk.car.upgrade.McuVersion parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.zk.car.upgrade.McuVersion parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.zk.car.upgrade.McuVersion parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.zk.car.upgrade.McuVersion parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.zk.car.upgrade.McuVersion parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.zk.car.upgrade.McuVersion parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.zk.car.upgrade.McuVersion parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.zk.car.upgrade.McuVersion parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.zk.car.upgrade.McuVersion prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code McuVersion}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.zk.car.upgrade.McuVersion, Builder> implements
      // @@protoc_insertion_point(builder_implements:McuVersion)
      com.zk.car.upgrade.McuVersionOrBuilder {
    // Construct using com.zk.car.upgrade.McuVersion.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>int32 mcu_upgrade_status = 1;</code>
     * @return The mcuUpgradeStatus.
     */
    @java.lang.Override
    public int getMcuUpgradeStatus() {
      return instance.getMcuUpgradeStatus();
    }
    /**
     * <code>int32 mcu_upgrade_status = 1;</code>
     * @param value The mcuUpgradeStatus to set.
     * @return This builder for chaining.
     */
    public Builder setMcuUpgradeStatus(int value) {
      copyOnWrite();
      instance.setMcuUpgradeStatus(value);
      return this;
    }
    /**
     * <code>int32 mcu_upgrade_status = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMcuUpgradeStatus() {
      copyOnWrite();
      instance.clearMcuUpgradeStatus();
      return this;
    }

    /**
     * <code>int32 mcu_request_payload_data = 2;</code>
     * @return The mcuRequestPayloadData.
     */
    @java.lang.Override
    public int getMcuRequestPayloadData() {
      return instance.getMcuRequestPayloadData();
    }
    /**
     * <code>int32 mcu_request_payload_data = 2;</code>
     * @param value The mcuRequestPayloadData to set.
     * @return This builder for chaining.
     */
    public Builder setMcuRequestPayloadData(int value) {
      copyOnWrite();
      instance.setMcuRequestPayloadData(value);
      return this;
    }
    /**
     * <code>int32 mcu_request_payload_data = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMcuRequestPayloadData() {
      copyOnWrite();
      instance.clearMcuRequestPayloadData();
      return this;
    }

    /**
     * <code>int32 mcu_upgrade_raedy_status = 3;</code>
     * @return The mcuUpgradeRaedyStatus.
     */
    @java.lang.Override
    public int getMcuUpgradeRaedyStatus() {
      return instance.getMcuUpgradeRaedyStatus();
    }
    /**
     * <code>int32 mcu_upgrade_raedy_status = 3;</code>
     * @param value The mcuUpgradeRaedyStatus to set.
     * @return This builder for chaining.
     */
    public Builder setMcuUpgradeRaedyStatus(int value) {
      copyOnWrite();
      instance.setMcuUpgradeRaedyStatus(value);
      return this;
    }
    /**
     * <code>int32 mcu_upgrade_raedy_status = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearMcuUpgradeRaedyStatus() {
      copyOnWrite();
      instance.clearMcuUpgradeRaedyStatus();
      return this;
    }

    /**
     * <code>int32 mcu_run_position = 4;</code>
     * @return The mcuRunPosition.
     */
    @java.lang.Override
    public int getMcuRunPosition() {
      return instance.getMcuRunPosition();
    }
    /**
     * <code>int32 mcu_run_position = 4;</code>
     * @param value The mcuRunPosition to set.
     * @return This builder for chaining.
     */
    public Builder setMcuRunPosition(int value) {
      copyOnWrite();
      instance.setMcuRunPosition(value);
      return this;
    }
    /**
     * <code>int32 mcu_run_position = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearMcuRunPosition() {
      copyOnWrite();
      instance.clearMcuRunPosition();
      return this;
    }

    /**
     * <code>int32 mcu_current_position_program_status = 5;</code>
     * @return The mcuCurrentPositionProgramStatus.
     */
    @java.lang.Override
    public int getMcuCurrentPositionProgramStatus() {
      return instance.getMcuCurrentPositionProgramStatus();
    }
    /**
     * <code>int32 mcu_current_position_program_status = 5;</code>
     * @param value The mcuCurrentPositionProgramStatus to set.
     * @return This builder for chaining.
     */
    public Builder setMcuCurrentPositionProgramStatus(int value) {
      copyOnWrite();
      instance.setMcuCurrentPositionProgramStatus(value);
      return this;
    }
    /**
     * <code>int32 mcu_current_position_program_status = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearMcuCurrentPositionProgramStatus() {
      copyOnWrite();
      instance.clearMcuCurrentPositionProgramStatus();
      return this;
    }

    /**
     * <code>int32 mcu_upgrade_fail = 6;</code>
     * @return The mcuUpgradeFail.
     */
    @java.lang.Override
    public int getMcuUpgradeFail() {
      return instance.getMcuUpgradeFail();
    }
    /**
     * <code>int32 mcu_upgrade_fail = 6;</code>
     * @param value The mcuUpgradeFail to set.
     * @return This builder for chaining.
     */
    public Builder setMcuUpgradeFail(int value) {
      copyOnWrite();
      instance.setMcuUpgradeFail(value);
      return this;
    }
    /**
     * <code>int32 mcu_upgrade_fail = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearMcuUpgradeFail() {
      copyOnWrite();
      instance.clearMcuUpgradeFail();
      return this;
    }

    /**
     * <code>int64 mcu_retransmission_block_num = 7;</code>
     * @return The mcuRetransmissionBlockNum.
     */
    @java.lang.Override
    public long getMcuRetransmissionBlockNum() {
      return instance.getMcuRetransmissionBlockNum();
    }
    /**
     * <code>int64 mcu_retransmission_block_num = 7;</code>
     * @param value The mcuRetransmissionBlockNum to set.
     * @return This builder for chaining.
     */
    public Builder setMcuRetransmissionBlockNum(long value) {
      copyOnWrite();
      instance.setMcuRetransmissionBlockNum(value);
      return this;
    }
    /**
     * <code>int64 mcu_retransmission_block_num = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearMcuRetransmissionBlockNum() {
      copyOnWrite();
      instance.clearMcuRetransmissionBlockNum();
      return this;
    }

    /**
     * <code>string mcu_pbl_version = 8;</code>
     * @return The mcuPblVersion.
     */
    @java.lang.Override
    public java.lang.String getMcuPblVersion() {
      return instance.getMcuPblVersion();
    }
    /**
     * <code>string mcu_pbl_version = 8;</code>
     * @return The bytes for mcuPblVersion.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMcuPblVersionBytes() {
      return instance.getMcuPblVersionBytes();
    }
    /**
     * <code>string mcu_pbl_version = 8;</code>
     * @param value The mcuPblVersion to set.
     * @return This builder for chaining.
     */
    public Builder setMcuPblVersion(
        java.lang.String value) {
      copyOnWrite();
      instance.setMcuPblVersion(value);
      return this;
    }
    /**
     * <code>string mcu_pbl_version = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearMcuPblVersion() {
      copyOnWrite();
      instance.clearMcuPblVersion();
      return this;
    }
    /**
     * <code>string mcu_pbl_version = 8;</code>
     * @param value The bytes for mcuPblVersion to set.
     * @return This builder for chaining.
     */
    public Builder setMcuPblVersionBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setMcuPblVersionBytes(value);
      return this;
    }

    /**
     * <code>string mcu_a_version = 9;</code>
     * @return The mcuAVersion.
     */
    @java.lang.Override
    public java.lang.String getMcuAVersion() {
      return instance.getMcuAVersion();
    }
    /**
     * <code>string mcu_a_version = 9;</code>
     * @return The bytes for mcuAVersion.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMcuAVersionBytes() {
      return instance.getMcuAVersionBytes();
    }
    /**
     * <code>string mcu_a_version = 9;</code>
     * @param value The mcuAVersion to set.
     * @return This builder for chaining.
     */
    public Builder setMcuAVersion(
        java.lang.String value) {
      copyOnWrite();
      instance.setMcuAVersion(value);
      return this;
    }
    /**
     * <code>string mcu_a_version = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearMcuAVersion() {
      copyOnWrite();
      instance.clearMcuAVersion();
      return this;
    }
    /**
     * <code>string mcu_a_version = 9;</code>
     * @param value The bytes for mcuAVersion to set.
     * @return This builder for chaining.
     */
    public Builder setMcuAVersionBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setMcuAVersionBytes(value);
      return this;
    }

    /**
     * <code>string mcu_b_version = 10;</code>
     * @return The mcuBVersion.
     */
    @java.lang.Override
    public java.lang.String getMcuBVersion() {
      return instance.getMcuBVersion();
    }
    /**
     * <code>string mcu_b_version = 10;</code>
     * @return The bytes for mcuBVersion.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMcuBVersionBytes() {
      return instance.getMcuBVersionBytes();
    }
    /**
     * <code>string mcu_b_version = 10;</code>
     * @param value The mcuBVersion to set.
     * @return This builder for chaining.
     */
    public Builder setMcuBVersion(
        java.lang.String value) {
      copyOnWrite();
      instance.setMcuBVersion(value);
      return this;
    }
    /**
     * <code>string mcu_b_version = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearMcuBVersion() {
      copyOnWrite();
      instance.clearMcuBVersion();
      return this;
    }
    /**
     * <code>string mcu_b_version = 10;</code>
     * @param value The bytes for mcuBVersion to set.
     * @return This builder for chaining.
     */
    public Builder setMcuBVersionBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setMcuBVersionBytes(value);
      return this;
    }

    /**
     * <code>string mcu_nvm_version = 11;</code>
     * @return The mcuNvmVersion.
     */
    @java.lang.Override
    public java.lang.String getMcuNvmVersion() {
      return instance.getMcuNvmVersion();
    }
    /**
     * <code>string mcu_nvm_version = 11;</code>
     * @return The bytes for mcuNvmVersion.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMcuNvmVersionBytes() {
      return instance.getMcuNvmVersionBytes();
    }
    /**
     * <code>string mcu_nvm_version = 11;</code>
     * @param value The mcuNvmVersion to set.
     * @return This builder for chaining.
     */
    public Builder setMcuNvmVersion(
        java.lang.String value) {
      copyOnWrite();
      instance.setMcuNvmVersion(value);
      return this;
    }
    /**
     * <code>string mcu_nvm_version = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearMcuNvmVersion() {
      copyOnWrite();
      instance.clearMcuNvmVersion();
      return this;
    }
    /**
     * <code>string mcu_nvm_version = 11;</code>
     * @param value The bytes for mcuNvmVersion to set.
     * @return This builder for chaining.
     */
    public Builder setMcuNvmVersionBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setMcuNvmVersionBytes(value);
      return this;
    }

    /**
     * <code>int32 mcu_upgrade_file_transfer_status = 12;</code>
     * @return The mcuUpgradeFileTransferStatus.
     */
    @java.lang.Override
    public int getMcuUpgradeFileTransferStatus() {
      return instance.getMcuUpgradeFileTransferStatus();
    }
    /**
     * <code>int32 mcu_upgrade_file_transfer_status = 12;</code>
     * @param value The mcuUpgradeFileTransferStatus to set.
     * @return This builder for chaining.
     */
    public Builder setMcuUpgradeFileTransferStatus(int value) {
      copyOnWrite();
      instance.setMcuUpgradeFileTransferStatus(value);
      return this;
    }
    /**
     * <code>int32 mcu_upgrade_file_transfer_status = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearMcuUpgradeFileTransferStatus() {
      copyOnWrite();
      instance.clearMcuUpgradeFileTransferStatus();
      return this;
    }

    /**
     * <code>string mcu_update_bean = 13;</code>
     * @return The mcuUpdateBean.
     */
    @java.lang.Override
    public java.lang.String getMcuUpdateBean() {
      return instance.getMcuUpdateBean();
    }
    /**
     * <code>string mcu_update_bean = 13;</code>
     * @return The bytes for mcuUpdateBean.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMcuUpdateBeanBytes() {
      return instance.getMcuUpdateBeanBytes();
    }
    /**
     * <code>string mcu_update_bean = 13;</code>
     * @param value The mcuUpdateBean to set.
     * @return This builder for chaining.
     */
    public Builder setMcuUpdateBean(
        java.lang.String value) {
      copyOnWrite();
      instance.setMcuUpdateBean(value);
      return this;
    }
    /**
     * <code>string mcu_update_bean = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearMcuUpdateBean() {
      copyOnWrite();
      instance.clearMcuUpdateBean();
      return this;
    }
    /**
     * <code>string mcu_update_bean = 13;</code>
     * @param value The bytes for mcuUpdateBean to set.
     * @return This builder for chaining.
     */
    public Builder setMcuUpdateBeanBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setMcuUpdateBeanBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:McuVersion)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.zk.car.upgrade.McuVersion();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "mcuUpgradeStatus_",
            "mcuRequestPayloadData_",
            "mcuUpgradeRaedyStatus_",
            "mcuRunPosition_",
            "mcuCurrentPositionProgramStatus_",
            "mcuUpgradeFail_",
            "mcuRetransmissionBlockNum_",
            "mcuPblVersion_",
            "mcuAVersion_",
            "mcuBVersion_",
            "mcuNvmVersion_",
            "mcuUpgradeFileTransferStatus_",
            "mcuUpdateBean_",
          };
          java.lang.String info =
              "\u0000\r\u0000\u0000\u0001\r\r\u0000\u0000\u0000\u0001\u0004\u0002\u0004\u0003\u0004" +
              "\u0004\u0004\u0005\u0004\u0006\u0004\u0007\u0002\b\u0208\t\u0208\n\u0208\u000b\u0208" +
              "\f\u0004\r\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.zk.car.upgrade.McuVersion> parser = PARSER;
        if (parser == null) {
          synchronized (com.zk.car.upgrade.McuVersion.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.zk.car.upgrade.McuVersion>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:McuVersion)
  private static final com.zk.car.upgrade.McuVersion DEFAULT_INSTANCE;
  static {
    McuVersion defaultInstance = new McuVersion();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      McuVersion.class, defaultInstance);
  }

  public static com.zk.car.upgrade.McuVersion getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<McuVersion> PARSER;

  public static com.google.protobuf.Parser<McuVersion> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

