// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: McuVersionPrefs.proto

package com.zk.car.upgrade;

public final class McuVersionPrefs {
  private McuVersionPrefs() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
